spring:
  application:
    name: dmscreen
  ai:
    mcp:
      server:
        name: dmscreen
        protocol: STREAMABLE
  flyway:
    validate-migration-naming: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate