spring:
  application:
    name: dmscreen
  profiles:
    default: dev
  ai:
    mcp:
      server:
        name: dmscreen
        protocol: STREAMABLE
  flyway:
    validate-migration-naming: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: aws
logging:
  structured:
    format:
      console: ecs
